my_movies_lists/src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title_name;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $create_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $edit_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Listname;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $privacy;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users", inversedBy="author")
     */
    private $users;

    public function __construct()
    {
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitleName(): ?string
    {
        return $this->title_name;
    }

    public function setTitleName(string $title_name): self
    {
        $this->title_name = $title_name;

        return $this;
    }

    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->create_date;
    }

    public function setCreateDate(?\DateTimeInterface $create_date): self
    {
        $this->create_date = $create_date;

        return $this;
    }

    public function getEditDate(): ?\DateTimeInterface
    {
        return $this->edit_date;
    }

    public function setEditDate(?\DateTimeInterface $edit_date): self
    {
        $this->edit_date = $edit_date;

        return $this;
    }

    public function getListname(): ?string
    {
        return $this->Listname;
    }

    public function setListname(?string $Listname): self
    {
        $this->Listname = $Listname;

        return $this;
    }

    public function getPrivacy(): ?bool
    {
        return $this->privacy;
    }

    public function setPrivacy(?bool $privacy): self
    {
        $this->privacy = $privacy;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }
}

my_movies_lists/src/Form/MovieType.php
<?php

namespace App\Form;

use App\Entity\Movie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MovieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Movie::class,
        ]);
    }
}

my_movies_lists/src/Controller/MovieController.php
<?php

namespace App\Controller;

use App\Entity\Movie;
use App\Form\MovieType;
use App\Repository\MovieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;

/**
 * @Route("/movie")
 */
class MovieController extends AbstractController
{
    /**
     * @Route("/", name="movie_index", methods={"GET"})
     */
    public function index(MovieRepository $movieRepository): Response
    {
        return $this->render('movie/index.html.twig', [
            'movies' => $movieRepository->findAll(),
        ]);
    }

    /**
     * @Route("/list", name="movie_list", methods={"GET"})
     */
    public function myList(MovieRepository $movieRepository): Response
    {
        dump($this->getUser());
        return $this->render('movie/index.html.twig', [
            'movies' => $movieRepository->findByUser($this->getUser()),
        ]);
    }

    /**
     * @Route("/new", name="movie_new", methods={"GET","POST"})
     * 
     */
    public function new(Request $request ): Response
    {
        $movie = new Movie();
        $title = $request->request->get('title');

        $movie->setTitleName($title);
        $movie->setCreateDate(new \DateTime);
        $movie->setPrivacy(false);
        $movie->setListname("favori");
        $movie->setUsers($this->getUser());
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($movie);
        $entityManager->flush();
        
        return new Response();
    }

    /**
     * @Route("/{id}", name="movie_show", methods={"GET"})
     */
    public function show(Movie $movie): Response
    {
        return $this->render('movie/show.html.twig', [
            'movie' => $movie,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="movie_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Movie $movie): Response
    {
        $form = $this->createForm(MovieType::class, $movie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('movie_index', [
                'id' => $movie->getId(),
            ]);
        }

        return $this->render('movie/edit.html.twig', [
            'movie' => $movie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="movie_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Movie $movie): Response
    {
        if ($this->isCsrfTokenValid('delete'.$movie->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($movie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('movie_index');
    }
}

my_movies_lists/templates/movie/_delete_form.html.twig
<form method="post" action="{{ path('movie_delete', {'id': movie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ movie.id) }}">
    <button class="btn">Delete</button>
</form>

my_movies_lists/templates/movie/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

my_movies_lists/templates/movie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Movie{% endblock %}

{% block body %}
    <h1>Edit Movie</h1>

    {{ include('movie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('movie_index') }}">back to list</a>

    {{ include('movie/_delete_form.html.twig') }}
{% endblock %}

my_movies_lists/templates/movie/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <h1>My movie list</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title_name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for movie in movies %}
            <tr>
                <td>{{ movie.id }}</td>
                <td>{{ movie.titleName }}</td>
                <td>
                    <a href="{{ path('movie_show', {'id': movie.id}) }}">show</a>
                    <a href="{{ path('movie_edit', {'id': movie.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('movie_new') }}">Create new</a>
{% endblock %}

my_movies_lists/templates/movie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Movie{% endblock %}

{% block body %}
    <h1>Create new Movie</h1>

    {{ include('movie/_form.html.twig') }}

    <a href="{{ path('movie_index') }}">back to list</a>
{% endblock %}

my_movies_lists/templates/movie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Movie{% endblock %}

{% block body %}
    <h1>Movie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ movie.id }}</td>
            </tr>
            <tr>
                <th>Title_name</th>
                <td>{{ movie.titleName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('movie_index') }}">back to list</a>

    <a href="{{ path('movie_edit', {'id': movie.id}) }}">edit</a>

    {{ include('movie/_delete_form.html.twig') }}
{% endblock %}