my_movies_lists/src/Entity/Users.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsersRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class Users implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_date;

    /**
 * @ORM\Column(type="datetime", nullable=true)
     */
    private $modify_date;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $profile_desc;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Movie", mappedBy="users")
     */
    private $author;

    public function __construct()
    {
        $this->roles = ['ROLE_USER'];
        $this->author = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->create_date;
    }


    public function setCreateDate(\DateTimeInterface $create_date): self
    {
        $this->create_date = $create_date;

        return $this;
    }

    public function getModifyDate(): ?\DateTimeInterface
    {
        return $this->modify_date;
    }

    public function setModifyDate(\DateTimeInterface $modify_date): self
    {
        $this->modify_date = $modify_date;

        return $this;
    }

    public function getProfileDesc(): ?string
    {
        return $this->profile_desc;
    }

    public function setProfileDesc(?string $profile_desc): self
    {
        $this->profile_desc = $profile_desc;

        return $this;
    }

    /**
     * @return Collection|Movie[]
     */
    public function getAuthor(): Collection
    {
        return $this->author;
    }

    public function addAuthor(Movie $author): self
    {
        if (!$this->author->contains($author)) {
            $this->author[] = $author;
            $author->setUsers($this);
        }

        return $this;
    }

    public function removeAuthor(Movie $author): self
    {
        if ($this->author->contains($author)) {
            $this->author->removeElement($author);
            // set the owning side to null (unless already changed)
            if ($author->getUsers() === $this) {
                $author->setUsers(null);
            }
        }

        return $this;
    }




}

my_movies_lists/src/Form/UsersType.php
<?php

namespace App\Form;

use App\Entity\Users;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UsersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('email')
            //->add('roles')
            ->add('password')
            //->add('create_date')
            //->add('modify_date')
            ->add('profile_desc')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Users::class,
        ]);
    }
}

my_movies_lists/src/Controller/UsersController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Form\UsersType;
use App\Repository\UsersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

/**
 * @Route("/users")
 */
class UsersController extends AbstractController
{
    /**
     * @Route("/", name="users_index", methods={"GET"})
     */
    public function index(UsersRepository $usersRepository): Response
    {
        return $this->render('users/index.html.twig', [
            'users' => $usersRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="users_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = new Users();        
        $form = $this->createForm(UsersType::class, $user);
        

        //$form->remove('roles');
        

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setCreateDate(new \DateTime());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();



            return $this->redirectToRoute('users_index'); 
        }

        return $this->render('users/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="users_show", methods={"GET"})
     */
    public function show(Users $user): Response
    {
        return $this->render('users/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="users_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Users $user): Response
    {
        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);
        //$form->remove('roles');
        //$form->add('roles', ChoiceType::class, ['choices' => ['member' => 'member']]);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('users_index', [
                'id' => $user->getId(),
            ]);
        }

        return $this->render('users/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="users_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Users $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('users_index');
    }
}

my_movies_lists/templates/users/_delete_form.html.twig
<form method="post" action="{{ path('users_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

my_movies_lists/templates/users/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Users{% endblock %}

{% block body %}
    <h1>Edit Users</h1>

    {{ include('users/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('users_index') }}">back to list</a>

    {{ include('users/_delete_form.html.twig') }}
{% endblock %}

my_movies_lists/templates/users/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Users index{% endblock %}

{% block body %}
    <h1>Users index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Password</th>
                <th>Username</th>
                <th>Create_date</th>
                <th>Modify_date</th>
                <th>Profile_desc</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.createDate ? user.createDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ user.modifyDate ? user.modifyDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ user.profileDesc }}</td>
                <td>
                    <a href="{{ path('users_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('users_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('users_new') }}">Create new</a>
{% endblock %}

my_movies_lists/templates/users/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Users{% endblock %}

{% block body %}
    <h1>Create new Users</h1>

    {{ include('users/_form.html.twig') }}

    <a href="{{ path('users_index') }}">back to list</a>
{% endblock %}

my_movies_lists/templates/users/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Users{% endblock %}

{% block body %}
    <h1>Users</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Create_date</th>
                <td>{{ user.createDate ? user.createDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Modify_date</th>
                <td>{{ user.modifyDate ? user.modifyDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Profile_desc</th>
                <td>{{ user.profileDesc }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('users_index') }}">back to list</a>

    <a href="{{ path('users_edit', {'id': user.id}) }}">edit</a>

    {{ include('users/_delete_form.html.twig') }}
{% endblock %}